language: c

install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh

script: bash -ex .travis-docker.sh

services:
  - docker

env:
  global:
    - PINS="string_metrics:."
    - DISTRO="ubuntu-16.04"
  matrix:
    - PACKAGE="string_metrics" OCAML_VERSION="4.07"

notifications:
  email: false
